version: '3'
services:
  webapp:
    image: shoot7/webapp
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./database:/app/database
    environment:
      MONGO_URL: mongodb://database:27017
    depends_on:
      - database
  database:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - /mongodb:/data/db
  test:
    image: shoot7/webapp
    depends_on:
      - webapp
    environment:
      - API_URL=http://webapp:3000
    command: ["yarn", "test"]
